[package]
authors = ["eater <hello@eaterofco.de>"]
name = "black-widow"
version = "0.1.0"

[dependencies]
bytes = "0.4.6"
docopt = "0.8.3"
futures = "0.1.20"
rustc-serialize = "0.3.24"
tokio = "0.1.4"
tokio-core = "0.1.16"
tokio-io = "0.1.6"
tokio-udp = "0.1.0"
tun-tap = "0.1.1"
