key = { value = "12345678901234567890123456789012" }
network-id = "shit son"

[server]
threads = 4
unix-socket = "/run/bw.sock"
port = 2121

[[network]]
type = "dns"
domain = "zer.ooo"

[interface]
mtu = 1400
name = "bw%d"
mode = "tap"

[auth]
secret = "help"

[router]
name = "dumb"

    [router.python]
    script = "python/example_router.py"
