[server]
threads = 4

[network]
code = "secret society"
# id = "2daf98dd678fc325e511d4333d6c4ff7d20156ac"

[interface]
mtu = 1400
name = "bw%d"
mode = "tap"

[auth]
secret = { value = "YiiBoi2018" }

[identity]
key = { value = "12345678901234567890123456789012" }
name = "Starving Califlower"

[router]
name = "dumb"

    [router.python]
    script = "python/example_router.py"